In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

In [14]:
df = pd.read_csv('/content/iris.csv')
df.head()

Sepal_Length   Sepal_Width   Petal_Length   Petal_Width        Class
0           5.1           3.5            1.4           0.2  Iris-setosa
1           4.9           3.0            1.4           0.2  Iris-setosa
2           4.7           3.2            1.3           0.2  Iris-setosa
3           4.6           3.1            1.5           0.2  Iris-setosa
4           5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
df.describe()

Sepal_Length   Sepal_Width   Petal_Length   Petal_Width
count    150.000000    150.000000     150.000000    150.000000
mean       5.843333      3.054000       3.758667      1.198667
std        0.828066      0.433594       1.764420      0.763161
min        4.300000      2.000000       1.000000      0.100000
25%        5.100000      2.800000       1.600000      0.300000
50%        5.800000      3.000000       4.350000      1.300000
75%        6.400000      3.300000       5.100000      1.800000
max        7.900000      4.400000       6.900000      2.500000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Sepal_Length   150 non-null    float64
 1    Sepal_Width   150 non-null    float64
 2    Petal_Length  150 non-null    float64
 3    Petal_Width   150 non-null    float64
 4   Class          150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [17]:
df['Class']=df['Class'].map({
    'Iris-setosa':0,
    'Iris-versicolor':1,
    'Iris-virginica':2
    
})
df.head(5)

Sepal_Length   Sepal_Width   Petal_Length   Petal_Width  Class
0           5.1           3.5            1.4           0.2      0
1           4.9           3.0            1.4           0.2      0
2           4.7           3.2            1.3           0.2      0
3           4.6           3.1            1.5           0.2      0
4           5.0           3.6            1.4           0.2      0

In [20]:
X = df[['Sepal_Length', ' Sepal_Width', ' Petal_Length', ' Petal_Width']]
X

Sepal_Length   Sepal_Width   Petal_Length   Petal_Width
0             5.1           3.5            1.4           0.2
1             4.9           3.0            1.4           0.2
2             4.7           3.2            1.3           0.2
3             4.6           3.1            1.5           0.2
4             5.0           3.6            1.4           0.2
..            ...           ...            ...           ...
145           6.7           3.0            5.2           2.3
146           6.3           2.5            5.0           1.9
147           6.5           3.0            5.2           2.0
148           6.2           3.4            5.4           2.3
149           5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [22]:
y=df[['Class']]
y

Class
0        0
1        0
2        0
3        0
4        0
..     ...
145      2
146      2
147      2
148      2
149      2

[150 rows x 1 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [24]:
from sklearn.tree import DecisionTreeClassifier
id3 = DecisionTreeClassifier(criterion='entropy')
id3_model = id3.fit(X_train, y_train)

In [26]:
y_id3 = id3_model.predict(X_test)
y_id3

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1])

In [27]:
accuracy = accuracy_score(y_test, y_id3)
recall = recall_score(y_test, y_id3, average='micro')
precision = precision_score(y_test, y_id3, average='micro')
f1 = f1_score(y_test, y_id3, average='micro')
print("Accuracy:", accuracy)
print("Error Rate:", 1.0-accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

Accuracy: 0.9555555555555556
Error Rate: 0.0444444444444444
Recall: 0.9555555555555556
Precision: 0.9555555555555556
F1 Score: 0.9555555555555556


In [34]:
from sklearn.metrics import classification_report,confusion_matrix
cm=confusion_matrix(y_test,y_id3)
cm

array([[14,  0,  0],
       [ 0, 17,  1],
       [ 0,  1, 12]])

In [29]:
print(classification_report(y_test,y_id3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [32]:
cart = DecisionTreeClassifier(criterion='gini')
cart_model = cart.fit(X_train, y_train)
y_cart = cart_model.predict(X_test)
y_cart

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1])

In [33]:
accuracy = accuracy_score(y_test, y_cart)
recall = recall_score(y_test, y_cart, average='micro')
precision = precision_score(y_test, y_cart, average='micro')
f1 = f1_score(y_test, y_cart, average='micro')
print("Accuracy:", accuracy)
print("Error Rate:", 1.0-accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 Score:", f1)

Accuracy: 0.9555555555555556
Error Rate: 0.0444444444444444
Recall: 0.9555555555555556
Precision: 0.9555555555555556
F1 Score: 0.9555555555555556


In [35]:
from sklearn.metrics import classification_report,confusion_matrix
cm=confusion_matrix(y_test,y_cart)
cm

array([[14,  0,  0],
       [ 0, 17,  1],
       [ 0,  1, 12]])

In [36]:
print(classification_report(y_test,y_id3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

